// <auto-generated />
using Classify.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Classify.Data.Migrations
{
    [DbContext(typeof(ClassifyContext))]
    [Migration("20260126170916_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Classify.Core.Domain.AudioFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MovementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.HasIndex("RecordingId");

                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("Classify.Core.Domain.Composer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Composers");
                });

            modelBuilder.Entity("Classify.Core.Domain.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("Classify.Core.Domain.PerformedMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.HasIndex("RecordingId");

                    b.ToTable("PerformedMovement");
                });

            modelBuilder.Entity("Classify.Core.Domain.ProposedMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudioFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComposerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConductorName")
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchReasoning")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovementNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovementTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudioFileId");

                    b.ToTable("ProposedMatch");
                });

            modelBuilder.Entity("Classify.Core.Domain.Recording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conductor")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("Classify.Core.Domain.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComposerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComposerId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("MovementRecording", b =>
                {
                    b.Property<int>("MovementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovementId", "RecordingId");

                    b.HasIndex("RecordingId");

                    b.ToTable("MovementRecording");
                });

            modelBuilder.Entity("Classify.Core.Domain.AudioFile", b =>
                {
                    b.HasOne("Classify.Core.Domain.Movement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classify.Core.Domain.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Classify.Core.Domain.Movement", b =>
                {
                    b.HasOne("Classify.Core.Domain.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Classify.Core.Domain.PerformedMovement", b =>
                {
                    b.HasOne("Classify.Core.Domain.Movement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classify.Core.Domain.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Classify.Core.Domain.ProposedMatch", b =>
                {
                    b.HasOne("Classify.Core.Domain.AudioFile", null)
                        .WithMany()
                        .HasForeignKey("AudioFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Classify.Core.Domain.Recording", b =>
                {
                    b.HasOne("Classify.Core.Domain.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Classify.Core.Domain.Work", b =>
                {
                    b.HasOne("Classify.Core.Domain.Composer", null)
                        .WithMany()
                        .HasForeignKey("ComposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovementRecording", b =>
                {
                    b.HasOne("Classify.Core.Domain.Movement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classify.Core.Domain.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
